/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author Vanz
 */
public class Booking extends javax.swing.JFrame {
    private String gender;
    private String specie;
    private String serv;
    
    
    
    String dataConn = "jdbc:mysql://localhost/teamhatdog";
    String username= "root";
    String password= "";
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public Booking() {
        
        this.buttonGroup1 = new ButtonGroup();
        initComponents();
        String dataConn = "jdbc:mysql://localhost/teamhatdog";
        String username= "root";
        String password= "";
        try{
            con= DriverManager.getConnection(dataConn,username,password);
        }catch(Exception e){
        }
        try{

                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(dataConn, username, password);
                ps = con.prepareStatement("SELECT * FROM `shop_schedule` WHERE `shop_schedule`.`status` = 'available'");
                rs = ps.executeQuery();
                 while(rs.next()){
                     String date = rs.getString("date");
                     dateCbBox.addItem(date);
                   }       
            }catch(Exception e){}
        
            String action1 = "SELECT * FROM `shop_schedule` WHERE `shop_schedule`.`status` = \"available\"";
            try{
                 PreparedStatement pst = con.prepareStatement(action1);
                 ResultSet rs =pst.executeQuery();
                 while(rs.next()){
                     String date = rs.getString("time_in");
                     timeCbBox.addItem(date);

                 }
            }catch(Exception e){
            }
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        menuPanel = new javax.swing.JPanel();
        schedNservicesLabel = new javax.swing.JLabel();
        bookingLabel = new javax.swing.JLabel();
        sampolNav = new javax.swing.JLabel();
        logoutbt = new javax.swing.JLabel();
        pawPatLabel = new javax.swing.JLabel();
        schedPanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        servLabel = new javax.swing.JLabel();
        dateCbBox = new javax.swing.JComboBox<>();
        submitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timeCbBox = new javax.swing.JComboBox<>();
        petNameTf = new javax.swing.JTextField();
        petAgeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        genderCb = new javax.swing.JComboBox<>();
        SpecieCb = new javax.swing.JComboBox<>();
        servCb = new javax.swing.JComboBox<>();
        usernameInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");

        menuPanel.setBackground(new java.awt.Color(9, 64, 103));

        schedNservicesLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        schedNservicesLabel.setForeground(new java.awt.Color(255, 255, 254));
        schedNservicesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedNservicesLabel.setText("Schedule and Services");
        schedNservicesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedNservicesLabelMouseClicked(evt);
            }
        });

        bookingLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        bookingLabel.setForeground(new java.awt.Color(255, 255, 254));
        bookingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingLabel.setText("Book Appointment");
        bookingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingLabelMouseClicked(evt);
            }
        });

        sampolNav.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        sampolNav.setForeground(new java.awt.Color(255, 255, 254));
        sampolNav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sampolNav.setText("My Appointments");
        sampolNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sampolNavMouseClicked(evt);
            }
        });

        logoutbt.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logoutbt.setForeground(new java.awt.Color(255, 255, 254));
        logoutbt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutbt.setText("Log Out");
        logoutbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtMouseClicked(evt);
            }
        });

        pawPatLabel.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        pawPatLabel.setForeground(new java.awt.Color(255, 255, 254));
        pawPatLabel.setText("PawPatrol");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(pawPatLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedNservicesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sampolNav, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutbt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(pawPatLabel)
                .addGap(18, 18, 18)
                .addComponent(bookingLabel)
                .addGap(18, 18, 18)
                .addComponent(schedNservicesLabel)
                .addGap(18, 18, 18)
                .addComponent(sampolNav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbt)
                .addContainerGap())
        );

        schedPanel.setBackground(new java.awt.Color(255, 255, 254));
        schedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dateLabel.setText("Select a Date");
        schedPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        servLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        servLabel.setText("Select  Service");
        schedPanel.add(servLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 123, -1));

        dateCbBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dateCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCbBoxActionPerformed(evt);
            }
        });
        schedPanel.add(dateCbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 244, -1));

        submitBTN.setBackground(new java.awt.Color(61, 169, 252));
        submitBTN.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 255, 254));
        submitBTN.setText("SUBMIT");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });
        schedPanel.add(submitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 86, 34));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setText("Select a Time");
        schedPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        timeCbBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        timeCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeCbBoxActionPerformed(evt);
            }
        });
        schedPanel.add(timeCbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 244, -1));

        petNameTf.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        schedPanel.add(petNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 148, -1));

        petAgeTf.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        schedPanel.add(petAgeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 77, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("Pet's Name");
        schedPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Age");
        schedPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MY PET");
        schedPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Gender");
        schedPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Species");
        schedPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        genderCb.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        schedPanel.add(genderCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        SpecieCb.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        SpecieCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cat", "Dog" }));
        schedPanel.add(SpecieCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        servCb.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        servCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Sitting", "Pet Walking", "Pet Grooming", "Pet Training", "Pet Hotel" }));
        schedPanel.add(servCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 116, -1));

        usernameInput.setEditable(false);
        usernameInput.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        schedPanel.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, 20));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Username");
        schedPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 64, 103));
        jLabel8.setText("PawPatrol > Appointment");
        schedPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(schedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(schedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void username(String user){
        usernameInput.setText(user);
    }
   
    private void schedNservicesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedNservicesLabelMouseClicked
        dispose();
        SchedandServs s = new SchedandServs();
        s.usernameInput.setText(usernameInput.getText());
        s.setVisible(true);
    }//GEN-LAST:event_schedNservicesLabelMouseClicked

    private void bookingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingLabelMouseClicked
        JOptionPane.showMessageDialog(this, "You are already in this display");
    }//GEN-LAST:event_bookingLabelMouseClicked

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        if (usernameInput.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Component!"); 
            } else {
            try{        
                String sub = "INSERT INTO `appointments` (`username`, `pet_name`, `pet_specie`, `pet_age`, `pet_gender`, `service`, `date_booked`, `time_booked`, `status`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, 'pending');";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(dataConn, username, password);
                PreparedStatement pst = con.prepareStatement(sub);

                pst.setString(1,usernameInput.getText());
                pst.setString(2,petNameTf.getText()); // gets pet name
                pst.setObject(3,SpecieCb.getSelectedItem()); // gets specie
                pst.setString(4,petAgeTf.getText()); // gets pet age
                pst.setObject(5,genderCb.getSelectedItem());// gets pet gender
                pst.setObject(6, servCb.getSelectedItem()); // gets service
                pst.setObject(7, dateCbBox.getSelectedItem()); // date
                pst.setObject(8, timeCbBox.getSelectedItem()); // time
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Successfully Updated");
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void dateCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCbBoxActionPerformed
       
    }//GEN-LAST:event_dateCbBoxActionPerformed

    private void timeCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeCbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeCbBoxActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        try {
            // TODO add your handling code here:
          
        } catch (Exception ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_usernameInputActionPerformed

    private void sampolNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sampolNavMouseClicked
        // TODO add your handling code here:    
        dispose();
        sampol s = new sampol();
        s.usernameInput.setText(usernameInput.getText());
        s.setVisible(true);
        
    }//GEN-LAST:event_sampolNavMouseClicked

    private void logoutbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtMouseClicked
        JFrame frame = new JFrame("Log Out");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to log out?", "Client", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_logoutbtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SpecieCb;
    private javax.swing.JLabel bookingLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> dateCbBox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> genderCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutbt;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel pawPatLabel;
    private javax.swing.JTextField petAgeTf;
    private javax.swing.JTextField petNameTf;
    private javax.swing.JLabel sampolNav;
    private javax.swing.JLabel schedNservicesLabel;
    private javax.swing.JPanel schedPanel;
    private javax.swing.JComboBox<String> servCb;
    private javax.swing.JLabel servLabel;
    private javax.swing.JButton submitBTN;
    private javax.swing.JComboBox<String> timeCbBox;
    public javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
